useSyntax("throw");//Is this how it should be?
print=import("print");
suites=[];
out=()=>out;
out.suite=(name,callback) {
	callback.name=name;
	suites.push(callback);
};
tests=[];
out.test=(name,callback) {
	callback.name=name;
	tests.push(callback);
};
out.assert=(a,b) {
	if(not(eq(a,b)),{
		throw("Assert failed!");
	});
};
out.run={
	suites.assyncEach((index,suite) {
		print("Now running suite \""+suite.name+"\"\n");
		try({
			tests.assyncForEach((index,test) {
				print("\tNow running test \""+test.name+"\"\n");
				try({
					test();
				},(err){
					print.err("\tSuite \""+test.name+"\" failed with err: \n"+err.msg"\n");
				});
			});
		},(err) {
			print.err("Suite \""+suite.name+"\" failed with err: \n"+err.msg"\n");
		});
	});
};
=<out;
